### ISSUE TITLE
Some food disappears every several ticks -- Does this means that winter comes?

### ISSUE THREAD

**Issue by Walden-Shen** [COBWEB-ca/cobweb2#2]

**Comment by COBWEB** [comment]
The default is to have seasonality in the food. You can change this in the resources tabBrad                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: ZewenSent: Monday, June 25, 2018 1:15 AMTo: COBWEB-ca/cobweb2Reply To: COBWEB-ca/cobweb2Cc: SubscribedSubject: [COBWEB-ca/cobweb2] Many foods disappear every several ticks -- Does this means that winter comes? (#2)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/COBWEB-ca/cobweb2/issues/2","url":"https://github.com/COBWEB-ca/cobweb2/issues/2","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/COBWEB-ca/cobweb2","title":"COBWEB-ca/cobweb2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/COBWEB-ca/cobweb2"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Many foods disappear every several ticks -- Does this means that winter comes? (#2)"}],"action":{"name":"View Issue","url":"https://github.com/COBWEB-ca/cobweb2/issues/2"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Many foods disappear every several ticks -- Does this means that winter comes? (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Zewen**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Walden-Shen",
"facts": [
{
"name": "Repository: ",
"value": "COBWEB-ca/cobweb2"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb2\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb2\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/COBWEB-ca/cobweb2/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349574990\n}"
}
],
"themeColor": "26292E"
}

**Comment by Walden-Shen** [comment]
Got it! Thank you.
