### ISSUE TITLE
Why are there so many agents gathering at the bottom/top of the window?

### ISSUE THREAD

**Issue by Walden-Shen** [COBWEB-ca/cobweb2#3]
I don't know if it's only me or something. And there is no food at the bottom/top of the window.

**Comment by COBWEB** [comment]
It is a quirk with some of AI seeds. Try changing the seeds in the AI tabBrad                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: ZewenSent: Monday, June 25, 2018 1:16 AMTo: COBWEB-ca/cobweb2Reply To: COBWEB-ca/cobweb2Cc: SubscribedSubject: [COBWEB-ca/cobweb2] Why are there so many agents gathering at the bottom/top of the window? (#3)I don't know if it's only me or something. And there is no food at the bottom/top of the window.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/COBWEB-ca/cobweb2/issues/3","url":"https://github.com/COBWEB-ca/cobweb2/issues/3","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/COBWEB-ca/cobweb2","title":"COBWEB-ca/cobweb2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/COBWEB-ca/cobweb2"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Why are there so many agents gathering at the bottom/top of the window? (#3)"}],"action":{"name":"View Issue","url":"https://github.com/COBWEB-ca/cobweb2/issues/3"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Why are there so many agents gathering at the bottom/top of the window? (#3)",
"sections": [
{
"text": "",
"activityTitle": "**Zewen**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Walden-Shen",
"facts": [
{
"name": "Repository: ",
"value": "COBWEB-ca/cobweb2"
},
{
"name": "Issue #: ",
"value": 3
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb2\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb2\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/COBWEB-ca/cobweb2/issues/3"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349575283\n}"
}
],
"themeColor": "26292E"
}

**Comment by Walden-Shen** [comment]
Got it. Thank you!
